# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

fastlane_version "2.28.3"

default_platform :android

platform :android do
  
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "submit to alpha"
  lane :alpha do
    version_code = increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )
    gradle(task: 'clean') 
    gradle(task: "assembleRelease")
    upload_to_play_store(track: 'alpha',
    skip_upload_metadata: true,
    skip_upload_images: true,           
    skip_upload_screenshots:  true               
    )
  end

  desc "promote alpha build to beta"
  lane :beta do
    upload_to_play_store(track: 'alpha', track_promote_to: 'beta')
  end

  # You can define as many lanes as you want

  # after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  # end

  # error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  # end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
